def options(room_type, furniture):
    for item in room_type and furniture:
        if room_type == "dining room" and furniture == "couch":
            return "ERROR! These don't mix!!"
        elif room_type == "dining room"and furniture == "bed":
            return "ERROR! These don't mix!!"
        else:
            return " "
print(options)

IkeaEssentials = [{"room_type": "bedroom", "furniture": "couch", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "couch", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "couch", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "couch", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "table", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "table", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "table", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "table", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "table", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "table", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "bed", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22turquoise%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "bed", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "bed", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "bed", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "bed", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "chair", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "chair", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "chair", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "chair", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "chair", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "light", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "light", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "light", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "light", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "bedroom", "furniture": "light", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "couch", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "couch", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "couch", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "couch", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "table", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "table", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "table", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "table", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "table", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "table", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "bed", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22turquoise%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "bed", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "bed", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "bed", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "bed", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=bed&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "chair", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "chair", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "chair", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "chair", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "chair", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "light", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "light", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "light", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "light", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "living room", "furniture": "light", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "table", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=couch&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "table", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "table", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "table", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "table", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "table", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=table&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "chair", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "chair", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "chair", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "chair", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "chair", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=chair&filter=unbxd_color_uFilter:%22red%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "light", "color": "blue", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "light", "color": "black", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22black%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "light", "color": "white", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22white%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "light", "color": "brown", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22brown%22&rows=40&view=grid&start=0"},
              {"room_type": "dining room", "furniture": "light", "color": "red", "URL": "https://www.ikea.com/ms/en_US/usearch/?&query=light&filter=unbxd_color_uFilter:%22blue%22&rows=40&view=grid&start=0"}]
              
MacysEssentials = [{"room_type": "bedroom", "furniture": "couch", "color": "blue", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Blue"},
              {"room_type": "bedroom", "furniture": "couch", "color": "black", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Black"},
              {"room_type": "bedroom", "furniture": "couch", "color": "white", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/White"},
              {"room_type": "bedroom", "furniture": "couch", "color": "brown", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Brown"},
              {"room_type": "bedroom", "furniture": "table", "color": "red", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Red"},
              {"room_type": "bedroom", "furniture": "table", "color": "blue", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Blue"},
              {"room_type": "bedroom", "furniture": "table", "color": "black", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Black"},
              {"room_type": "bedroom", "furniture": "table", "color": "white", "URL": "https://www.macys.com/shop/featured/table/Color_normal/White"},
              {"room_type": "bedroom", "furniture": "table", "color": "brown", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Brown"},
              {"room_type": "bedroom", "furniture": "table", "color": "red", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Red"},
              {"room_type": "bedroom", "furniture": "bed", "color": "blue", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Blue"},
              {"room_type": "bedroom", "furniture": "bed", "color": "black", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Black"},
              {"room_type": "bedroom", "furniture": "bed", "color": "white", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/White"},
              {"room_type": "bedroom", "furniture": "bed", "color": "brown", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Brown"},
              {"room_type": "bedroom", "furniture": "bed", "color": "red", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Red"},
              {"room_type": "bedroom", "furniture": "chair", "color": "blue", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Blue"},
              {"room_type": "bedroom", "furniture": "chair", "color": "black", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Black"},
              {"room_type": "bedroom", "furniture": "chair", "color": "white", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/White"},
              {"room_type": "bedroom", "furniture": "chair", "color": "brown", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Brown"},
              {"room_type": "bedroom", "furniture": "chair", "color": "red", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Red"},
              {"room_type": "bedroom", "furniture": "light", "color": "blue", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Blue"},
              {"room_type": "bedroom", "furniture": "light", "color": "black", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Black"},
              {"room_type": "bedroom", "furniture": "light", "color": "white", "URL": "https://www.macys.com/shop/featured/light/Color_normal/White"},
              {"room_type": "bedroom", "furniture": "light", "color": "brown", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Brown"},
              {"room_type": "bedroom", "furniture": "light", "color": "red", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Brown"},
              {"room_type": "living room", "furniture": "couch", "color": "blue", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Blue"},
              {"room_type": "living room", "furniture": "couch", "color": "black", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Black"},
              {"room_type": "living room", "furniture": "couch", "color": "white", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/White"},
              {"room_type": "living room", "furniture": "couch", "color": "brown", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Brown"},
              {"room_type": "living room", "furniture": "table", "color": "red", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Red"},
              {"room_type": "living room", "furniture": "table", "color": "blue", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Blue"},
              {"room_type": "living room", "furniture": "table", "color": "black", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Black"},
              {"room_type": "living room", "furniture": "table", "color": "white", "URL": "https://www.macys.com/shop/featured/table/Color_normal/White"},
              {"room_type": "living room", "furniture": "table", "color": "brown", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Brown"},
              {"room_type": "living room", "furniture": "table", "color": "red", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Red"},
              {"room_type": "living room", "furniture": "bed", "color": "blue", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Blue"},
              {"room_type": "living room", "furniture": "bed", "color": "black", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Black"},
              {"room_type": "living room", "furniture": "bed", "color": "white", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/White"},
              {"room_type": "living room", "furniture": "bed", "color": "brown", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Brown"},
              {"room_type": "living room", "furniture": "bed", "color": "red", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Red"},
              {"room_type": "living room", "furniture": "chair", "color": "blue", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Blue"},
              {"room_type": "living room", "furniture": "chair", "color": "black", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Black"},
              {"room_type": "living room", "furniture": "chair", "color": "white", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/White"},
              {"room_type": "living room", "furniture": "chair", "color": "brown", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Brown"},
              {"room_type": "living room", "furniture": "chair", "color": "red", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Red"},
              {"room_type": "living room", "furniture": "light", "color": "blue", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Blue"},
              {"room_type": "living room", "furniture": "light", "color": "black", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Blue"},
              {"room_type": "living room", "furniture": "light", "color": "white", "URL": "https://www.macys.com/shop/featured/light/Color_normal/White"},
              {"room_type": "living room", "furniture": "light", "color": "brown", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Brown"},
              {"room_type": "living room", "furniture": "light", "color": "red", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Blue"},
              {"room_type": "dining room", "furniture": "couch", "color": "blue", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Blue"},
              {"room_type": "dining room", "furniture": "couch", "color": "black", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Black"},
              {"room_type": "dining room", "furniture": "couch", "color": "white", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/White"},
              {"room_type": "dining room", "furniture": "couch", "color": "brown", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Brown"},
              {"room_type": "dining room", "furniture": "table", "color": "red", "URL": "https://www.macys.com/shop/featured/couch/Color_normal/Red"},
              {"room_type": "dining room", "furniture": "table", "color": "blue", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Blue"},
              {"room_type": "dining room", "furniture": "table", "color": "black", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Black"},
              {"room_type": "dining room", "furniture": "table", "color": "white", "URL": "https://www.macys.com/shop/featured/table/Color_normal/White"},
              {"room_type": "dining room", "furniture": "table", "color": "brown", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Brown"},
              {"room_type": "dining room", "furniture": "table", "color": "red", "URL": "https://www.macys.com/shop/featured/table/Color_normal/Red"},
              {"room_type": "dining room", "furniture": "bed", "color": "blue", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Blue"},
              {"room_type": "dining room", "furniture": "bed", "color": "black", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Black"},
              {"room_type": "dining room", "furniture": "bed", "color": "white", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/White"},
              {"room_type": "dining room", "furniture": "bed", "color": "brown", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Brown"},
              {"room_type": "dining room", "furniture": "bed", "color": "red", "URL": "https://www.macys.com/shop/featured/bed/Color_normal/Red"},
              {"room_type": "dining room", "furniture": "chair", "color": "blue", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Blue"},
              {"room_type": "dining room", "furniture": "chair", "color": "black", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Black"},
              {"room_type": "dining room", "furniture": "chair", "color": "white", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/White"},
              {"room_type": "dining room", "furniture": "chair", "color": "brown", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Brown"},
              {"room_type": "dining room", "furniture": "chair", "color": "red", "URL": "https://www.macys.com/shop/featured/chair/Color_normal/Red"},
              {"room_type": "dining room", "furniture": "light", "color": "blue", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Blue"},
              {"room_type": "dining room", "furniture": "light", "color": "black", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Blue"},
              {"room_type": "dining room", "furniture": "light", "color": "white", "URL": "https://www.macys.com/shop/featured/light/Color_normal/White"},
              {"room_type": "dining room", "furniture": "light", "color": "brown", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Brown"},
              {"room_type": "dining room", "furniture": "light", "color": "red", "URL": "https://www.macys.com/shop/featured/light/Color_normal/Blue"}]
              
def IkeaURLs(furniture, color):
    for item in IkeaEssentials:
        if furniture == item['furniture'] and color == item['color']:
            return (item['URL'])